/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rcc_rpc_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace janus {


DepId::~DepId() noexcept {
}


void DepId::__set_str(const std::string& val) {
  this->str = val;
}

void DepId::__set_id(const int64_t val) {
  this->id = val;
}
std::ostream& operator<<(std::ostream& out, const DepId& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t DepId::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->str);
          this->__isset.str = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->id);
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t DepId::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("DepId");

  xfer += oprot->writeFieldBegin("str", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->str);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(DepId &a, DepId &b) {
  using ::std::swap;
  swap(a.str, b.str);
  swap(a.id, b.id);
  swap(a.__isset, b.__isset);
}

DepId::DepId(const DepId& other0) {
  str = other0.str;
  id = other0.id;
  __isset = other0.__isset;
}
DepId& DepId::operator=(const DepId& other1) {
  str = other1.str;
  id = other1.id;
  __isset = other1.__isset;
  return *this;
}
void DepId::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "DepId(";
  out << "str=" << to_string(str);
  out << ", " << "id=" << to_string(id);
  out << ")";
}

} // namespace
