site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:11001", "s201:11002", "s301:11003", "s401:11004", "s501:11005"]
  client: # each line is a partition
    - ["c101"]

# process_name - host_addr map
process:
  s101: p1
  s201: p2
  s301: p3
  s401: p4
  s501: p5
  c101: localhost


# 5 process - group by name

host:
  p1: 172.20.0.11
  p2: 172.20.0.12
  p3: 172.20.0.13
  p4: 172.20.0.14
  p5: 172.20.0.15

